# Generated by Django 4.0 on 2022-01-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_ad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='is_activ',
            new_name='is_active',
        ),
    ]
