# Generated by Django 4.0 on 2022-01-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_is_activ_ad_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='posts',
        ),
    ]
