# Generated by Django 4.0 on 2021-12-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_author_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
