# Generated by Django 4.0 on 2021-12-13 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_user_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='users',
        ),
        migrations.AddField(
            model_name='comment',
            name='comments',
            field=models.TextField(null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.comment', verbose_name='Comments'),
        ),
    ]
