# Generated by Django 4.0 on 2021-12-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_comment_users_comment_comments_user_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.CharField(max_length=255, null=True, verbose_name='Comments'),
        ),
    ]
